export const novosEventosJson = [
  {
    cliente: 'ODONTOPREV | DR 3T22 | 27/10 10h',
    data: '27/10/2022',
    hora: '10:00',
    proprietario: 'ALINE',
    tocarEvento: 'ALINE',
    contaZoom: '500',
    gravacaoIngles: 'MICHELLE',
    linkOficialEvento:
      'https://tenmeetings.com.br/ten-events/#/webinar?evento=VideoconferenciadeResultados3T22-Odontoprev_396',
    linkGravacaoEN:
      'https://us06web.zoom.us/w/83805934698?tk=iSPvk6zk9m1BHFbh3eqnavG9QjpfoimoCgzH3s-9vVs.DQMAAAATgzkUahZoMzMyWTRPaVNBdVAzaTVFNTU0S1lnAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA',
  },
  {
    cliente: 'Assaí | DR 3T22 | 27/10 11h',
    data: '21/10/2022',
    hora: '11:00',
    proprietario: 'VENTURA',
    tocarEvento: 'VENTURA',
    contaZoom: '1000',
    gravacaoIngles: 'GABI',
    linkOficialEvento:
      'https://tenmeetings.com.br/ten-events/#/webinar?evento=TeleconferenciadeResultados-3T22_812',
    linkGravacaoEN:
      'https://us06web.zoom.us/w/83050884595?tk=sCAxHP98KNsJ96aJ3qNRS825qenaAjDtElOW0R4ZXnY.DQMAAAATVjft8xY5Q0xXbTg5RVJHdXEyR3JKQ1NMX2tBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA',
  },
  {
    cliente: 'ISA CTEEP | DR 3T22 | 28/10 10h',
    data: '28/10/2022',
    hora: '10:00',
    proprietario: 'RUSSO',
    tocarEvento: 'RUSSO',
    contaZoom: '500',
    gravacaoIngles: 'MICHELLE',
    linkOficialEvento:
      'https://tenmeetings.com.br/ten-events/#/webinar?evento=ConferenciadeResultados3T22_651',
    linkGravacaoEN: '',
  },
  {
    cliente: 'INTELBRAS | DR 3T22 | 01/11 11h',
    data: '01/11/2022',
    hora: '11:00',
    proprietario: 'ALINE',
    tocarEvento: 'ALINE',
    contaZoom: '500',
    gravacaoIngles: 'MICHELLE',
    linkOficialEvento:
      'https://tenmeetings.com.br/ten-events/#/webinar?evento=Intelbras-3T22_500',
    linkGravacaoEN: '',
  },
  {
    cliente: 'GPA | DR 3T22 | 04/11 10hs',
    data: '04/11/2022',
    hora: '10:00',
    proprietario: 'ALINE',
    tocarEvento: 'ALINE',
    contaZoom: '1000',
    gravacaoIngles: 'MICHELLE',
    linkOficialEvento:
      'https://tenmeetings.com.br/ten-events/#/webinar?evento=ConferênciadeResultados3T22_777',
    linkGravacaoEN: '',
  },
  {
    cliente: 'Três Tentos Agro | DR 3T22 | 08/11 10h',
    data: '08/11/2022',
    hora: '11:00',
    proprietario: 'BRENNO',
    tocarEvento: 'BRENNO',
    contaZoom: '500',
    gravacaoIngles: 'VENTURA',
    linkOficialEvento:
      'https://tenmeetings.com.br/ten-events/#/webinar?evento=ConferênciadeResultados-3T22TrêsTentosAgro_924',
    linkGravacaoEN: '',
  },
  {
    cliente: 'Banco Modal | DR 3T22| 08/11 11h',
    data: '08/11/2022',
    hora: '11:00',
    proprietario: 'RUSSO',
    tocarEvento: 'RUSSO',
    contaZoom: '500',
    gravacaoIngles: 'MICHELLE',
    linkOficialEvento:
      'https://tenmeetings.com.br/ten-events/#/webinar?evento=ConferenciadeResultados3T22-Modal_874',
    linkGravacaoEN: '',
  },
  {
    cliente: 'ENGIE | DR 3T22 | 09/11 11h',
    data: '09/11/2022',
    hora: '11:00',
    proprietario: 'GABI',
    tocarEvento: 'VENTURA',
    contaZoom: '500',
    gravacaoIngles: 'LUAN EN e BRENNO PT',
    linkOficialEvento:
      'https://tenmeetings.com.br/ten-events/#/webinar?evento=Engie-3T22_915',
    linkGravacaoEN: '',
  },
  {
    cliente: 'BOA VISTA | DR 3T22 | 10/11 11h',
    data: '10/11/2022',
    hora: '11:00',
    proprietario: 'RUSSO',
    tocarEvento: 'RUSSO',
    contaZoom: '500',
    gravacaoIngles: 'RUSSO',
    linkOficialEvento:
      'https://tenmeetings.com.br/ten-events/#/webinar?evento=BOAS3-ConferenciadeResultados3T22_918',
    linkGravacaoEN: '',
  },
  {
    cliente: 'Gerdau | DR 3T22 (Imprensa) | 09/11 11h',
    data: '09/11/2022',
    hora: '11:00',
    proprietario: 'ALINE',
    tocarEvento: 'ALINE',
    contaZoom: '500',
    gravacaoIngles: 'MICHELLE',
    linkOficialEvento:
      'https://tenmeetings.com.br/ten-events/#/webinar?evento=VideoconferênciadeResultados3T22-Gerdau(Imprensa)_795',
    linkGravacaoEN: '',
  },
  {
    cliente: 'Gerdau | DR 3T22 (Analistas/Investidores) | 09/11 14h',
    data: '09/11/2022',
    hora: '14:00',
    proprietario: 'ALINE',
    tocarEvento: 'ALINE',
    contaZoom: '500',
    gravacaoIngles: 'MICHELLE E BRENNO',
    linkOficialEvento:
      'https://tenmeetings.com.br/ten-events/#/webinar?evento=VideoconferênciadeResultados3T22-Gerdau(Analistas/Investidores)_870',
    linkGravacaoEN:
      'https://us06web.zoom.us/w/89487442275?tk=HPTPkicGmWuOijWbpjyeY2r-eyG7XxurBvHX6QvfYM8.DQMAAAAU1d4BYxZHTTRuSmVYMVN5ZXJ1YlY1dmJTU1lBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA',
  },
  {
    cliente: 'ELETROBRAS | DR 3T22 | 10/11 14:30h',
    data: '10/11/2022',
    hora: '14:30',
    proprietario: 'RUSSO',
    tocarEvento: 'RUSSO E GUSTAVO',
    contaZoom: '500',
    gravacaoIngles: 'RUSSO E MICHELLE',
    linkOficialEvento:
      'https://tenmeetings.com.br/ten-events/#/webinar?evento=ConferenciadeResultados3T22-Eletrobras_220',
    linkGravacaoEN: '',
  },
  {
    cliente: 'Azul | DR 3T22 | 10/11 12h (EN)',
    data: '10/11/2022',
    hora: '12:00',
    proprietario: 'BRENNO',
    tocarEvento: 'PAULO R. + OTÁVIO + GABRIEL',
    contaZoom: '1000',
    gravacaoIngles: 'NÃO TEM',
    linkOficialEvento:
      'https://tenmeetings.com.br/ten-events/#/webinar?evento=ResultsConferenceAzul3Q22_129',
    linkGravacaoEN: '',
  },
  {
    cliente: 'Porto Seguro | DR 3T22 | 10/11 11h',
    data: '10/11/2022',
    hora: '11:00',
    proprietario: 'GABI',
    tocarEvento: 'JEAN',
    contaZoom: '500',
    gravacaoIngles: 'VINICIUS',
    linkOficialEvento:
      'https://tenmeetings.com.br/ten-events/#/webinar?evento=Porto-3T22_880',
    linkGravacaoEN: '',
  },
  {
    cliente: 'HELBOR | DR 3T22 | 11/11 15h',
    data: '11/11/2022',
    hora: '15:00',
    proprietario: 'GABI',
    tocarEvento: 'GABI',
    contaZoom: '500',
    gravacaoIngles: 'KENJI',
    linkOficialEvento:
      'https://tenmeetings.com.br/ten-events/#/webinar?evento=Helbor-3T22_480',
    linkGravacaoEN: '',
  },
  {
    cliente: 'Grupo Carrefour Brasil | DR 3T22 | 10/11 10h',
    data: '10/11/2022',
    hora: '10:00',
    proprietario: 'RUSSO',
    tocarEvento: 'SOUSA E MORENO',
    contaZoom: '1000',
    gravacaoIngles: 'DANILO',
    linkOficialEvento:
      'https://tenmeetings.com.br/ten-events/#/webinar?evento=ConferenciadeResultados3T22-Carrefour_769',
    linkGravacaoEN: '',
  },
  {
    cliente: 'Cosan | DR 3T22 | 14/11 14h',
    data: '14/11/2022',
    hora: '14:00',
    proprietario: 'VENTURA',
    tocarEvento: 'VENTURA',
    contaZoom: '1000',
    gravacaoIngles: 'LUAN',
    linkOficialEvento:
      'https://tenmeetings.com.br/ten-events/#/webinar?evento=ConferênciadeResultados3T22_204',
    linkGravacaoEN: '',
  },
  {
    cliente: 'Ferbasa | DR 3T22 | 14/11 15h',
    data: '14/11/2022',
    hora: '15:00',
    proprietario: 'GABI',
    tocarEvento: 'GABI',
    contaZoom: '500',
    gravacaoIngles: 'BRENNO',
    linkOficialEvento:
      'https://tenmeetings.com.br/ten-events/#/webinar?evento=Ferbasa-3T22_388',
    linkGravacaoEN: '',
  },
  {
    cliente: 'FRASLE | DR 3T22 | 10/11 11h',
    data: '10/11/2022',
    hora: '11:00',
    proprietario: 'VENTURA',
    tocarEvento: 'MICHELLE',
    contaZoom: '500',
    gravacaoIngles: 'PEDRO HENRIQUE',
    linkOficialEvento:
      'https://tenmeetings.com.br/ten-events/#/webinar?evento=ConferenciadeResultados3T22_666',
    linkGravacaoEN: '',
  },
  {
    cliente: 'IOCHPE | DR 3T22 | 10/11 10h',
    data: '10/11/2022',
    hora: '10:00',
    proprietario: 'RUSSO',
    tocarEvento: 'VENTURA',
    contaZoom: '500',
    gravacaoIngles: 'DANI MARKETING',
    linkOficialEvento:
      'https://tenmeetings.com.br/ten-events/#/webinar?evento=ConferenciadeResultados3T22-Iochpe-Maxion_944',
    linkGravacaoEN: '',
  },
  {
    cliente: 'POSITIVO | DR 3T22 | 10/11 14:30h',
    data: '10/11/2022',
    hora: '14:30',
    proprietario: 'ALINE',
    tocarEvento: 'ALINE',
    contaZoom: '500',
    gravacaoIngles: 'FELIPE',
    linkOficialEvento:
      'https://tenmeetings.com.br/ten-events/#/webinar?evento=Positivo-3T22_327',
    linkGravacaoEN: '',
  },
  {
    cliente: 'BBM | DR 3T22 | 11/11 11h',
    data: '11/11/2022',
    hora: '11:00',
    proprietario: 'GABI',
    tocarEvento: 'BRENNO E DANILO',
    contaZoom: '500',
    gravacaoIngles: 'NÃO TEM',
    linkOficialEvento:
      'https://tenmeetings.com.br/ten-events/#/webinar?evento=BBM-3T22_905',
    linkGravacaoEN: '',
  },
  {
    cliente: 'VITTIA | DR 3T22 | 11/11 10h',
    data: '11/11/2022',
    hora: '10:00',
    proprietario: 'VENTURA',
    tocarEvento: 'SOUSA E MORENO',
    contaZoom: '500',
    gravacaoIngles: 'VINICIUS',
    linkOficialEvento:
      'https://tenmeetings.com.br/ten-events/#/webinar?evento=ConferenciadeResultados3T22_269',
    linkGravacaoEN: '',
  },
  {
    cliente: 'Hapvida | DR 3T22 | 10/11 11h',
    data: '10/11/2022',
    hora: '11:00',
    proprietario: 'ALINE',
    tocarEvento: 'BRENNO E DANILO',
    contaZoom: '3000',
    gravacaoIngles: 'LUAN',
    linkOficialEvento:
      'https://tenmeetings.com.br/ten-events/#/webinar?evento=Hapvida3T22_869',
    linkGravacaoEN: '',
  },
  {
    cliente: 'Oi | DR 3T22 | 10/11 11h',
    data: '10/11/2022',
    hora: '11:00',
    proprietario: 'RUSSO',
    tocarEvento: 'IAN',
    contaZoom: '3000',
    gravacaoIngles: 'ALINE VALENTIM',
    linkOficialEvento:
      'https://tenmeetings.com.br/ten-events/#/webinar?evento=ResultsConference3Q22_222',
    linkGravacaoEN: '',
  },
  {
    cliente: 'Priner | DR 3T22 | 11/11 09:30h',
    data: '11/11/2022',
    hora: '09:30',
    proprietario: 'BRENNO',
    tocarEvento: 'VENTURA/JEAN',
    contaZoom: '500',
    gravacaoIngles: 'NÃO TEM',
    linkOficialEvento:
      'https://tenmeetings.com.br/ten-events/#/webinar?evento=ConferênciadeResultados-3T22Priner_125',
    linkGravacaoEN: '',
  },
  {
    cliente: 'MILLS | DR 3T22 | 11/11 11h',
    data: '11/11/2022',
    hora: '11:00',
    proprietario: 'RUSSO',
    tocarEvento: 'ALINE',
    contaZoom: '500',
    gravacaoIngles: 'FELIPE',
    linkOficialEvento:
      'https://tenmeetings.com.br/ten-events/#/webinar?evento=ConferenciadeResultados3T22-Mills_984',
    linkGravacaoEN: '',
  },
  {
    cliente: 'Mercantil | DR 3T22 |  11/11 10h',
    data: '11/11/2022',
    hora: '10:00',
    proprietario: 'GABI',
    tocarEvento: 'GABI',
    contaZoom: '500',
    gravacaoIngles: 'KENJI',
    linkOficialEvento:
      'https://tenmeetings.com.br/ten-events/#/webinar?evento=Mercantil-3T22_268',
    linkGravacaoEN: '',
  },
  {
    cliente: 'Randon | DR 3T22 | 11/11 11h',
    data: '11/11/2022',
    hora: '11:00',
    proprietario: 'GABI',
    tocarEvento: 'GUSTAVO E MATHEUS',
    contaZoom: '500',
    gravacaoIngles: 'ALINE VALENTIM',
    linkOficialEvento:
      'https://tenmeetings.com.br/ten-events/#/webinar?evento=Randon-3T22_178',
    linkGravacaoEN: '',
  },
  {
    cliente: 'Multilaser | DR 3T22 | 11/11 09h',
    data: '11/11/2022',
    hora: '09:00',
    proprietario: 'VENTURA',
    tocarEvento: 'MICHELLE E IAN',
    contaZoom: '500',
    gravacaoIngles: 'DANI MARKETING',
    linkOficialEvento:
      'https://tenmeetings.com.br/ten-events/#/webinar?evento=ConferenciadeResultados3T22_155',
    linkGravacaoEN: '',
  },
  {
    cliente: 'Vivara | DR 3T22 | 11/11 11h',
    data: '11/11/2022',
    hora: '11:00',
    proprietario: 'VENTURA',
    tocarEvento: 'VENTURA',
    contaZoom: '500',
    gravacaoIngles: 'IAN',
    linkOficialEvento:
      'https://tenmeetings.com.br/ten-events/#/webinar?evento=vivara3T22_869',
    linkGravacaoEN: '',
  },
  {
    cliente: 'PETRORECONCAVO | DR 3T22 | 11/11 10h',
    data: '11/11/2022',
    hora: '10:00',
    proprietario: 'VENTURA',
    tocarEvento: 'PAULO R.',
    contaZoom: '500',
    gravacaoIngles: 'Pedro Kuhn',
    linkOficialEvento:
      'https://tenmeetings.com.br/ten-events/#/webinar?evento=ConferenciadeResultados3T22_264',
    linkGravacaoEN: '',
  },
  {
    cliente: 'ENERGISA | DR 3T22 | 11/11 15h',
    data: '11/11/2022',
    hora: '15:00',
    proprietario: 'ALINE',
    tocarEvento: 'ALINE',
    contaZoom: '1000',
    gravacaoIngles: 'PAULO ROBERTO',
    linkOficialEvento:
      'https://tenmeetings.com.br/ten-events/#/webinar?evento=ENERGISA3T22_461',
    linkGravacaoEN: '',
  },
  {
    cliente: 'AGROGALAXY | DR 3T22 | 16/11 11h',
    data: '16/11/2022',
    hora: '11:00',
    proprietario: 'ALINE',
    tocarEvento: 'ALINE',
    contaZoom: '500',
    gravacaoIngles: 'BRENNO',
    linkOficialEvento:
      'https://tenmeetings.com.br/ten-events/#/webinar?evento=Agrogalaxy-3T22_311',
    linkGravacaoEN: '',
  },
  {
    cliente: 'Eucatex | ID | 11/11 11h',
    data: '11/11/2022',
    hora: '11:00',
    proprietario: 'RUSSO',
    tocarEvento: 'MICHELLE E IAN',
    contaZoom: '500',
    gravacaoIngles: 'NÃO TEM',
    linkOficialEvento: 'https://tenmeetings.com.br/tenlive/#/t/eucatexday',
    linkGravacaoEN: '',
  },
  {
    cliente: 'Zenvia | DR 3T22 | 17/11 12h (EN)',
    data: '17/11/2022',
    hora: '12:00',
    proprietario: 'ALINE',
    tocarEvento: 'GABI',
    contaZoom: '500',
    gravacaoIngles: 'NÃO TEM',
    linkOficialEvento:
      'https://tenmeetings.com.br/ten-events/#/webinar?evento=Zenvia-3Q22_727',
    linkGravacaoEN: '',
  },
  {
    cliente: 'BRISANET | DR 3T22 | 17/11 13h',
    data: '17/11/2022',
    hora: '13:00',
    proprietario: 'ALINE',
    tocarEvento: 'RUSSO',
    contaZoom: '500',
    gravacaoIngles: 'GABI',
    linkOficialEvento:
      'https://tenmeetings.com.br/ten-events/#/webinar?evento=Brisanet3T22_106',
    linkGravacaoEN: '',
  },
  {
    cliente: 'Agribrasil | DR 3T22 |  11/11 17:30h',
    data: '11/11/2022',
    hora: '17:30',
    proprietario: 'ALINE',
    tocarEvento: 'ALINE',
    contaZoom: '500',
    gravacaoIngles: 'PAULO ROBERTO',
    linkOficialEvento:
      'https://tenmeetings.com.br/ten-events/#/webinar?evento=Agribrasil3T22_409',
    linkGravacaoEN: '',
  },
  {
    cliente: 'Banco Inter | DR 3T22 | 09/11 11h (EN)',
    data: '09/11/2022',
    hora: '11:00',
    proprietario: 'GABI',
    tocarEvento: 'GABI',
    contaZoom: '3000',
    gravacaoIngles: 'PEDRO HENRIQUE',
    linkOficialEvento:
      'https://tenmeetings.com.br/ten-events/#/webinar?evento=BancoInter-3T22_405',
    linkGravacaoEN: '',
  },
  {
    cliente: 'Riachuelo | DR 3T22 | 10/11 13h',
    data: '10/11/2022',
    hora: '13:00',
    proprietario: 'VENTURA',
    tocarEvento: 'VENTURA',
    contaZoom: '500',
    gravacaoIngles: 'DANI MARKETING',
    linkOficialEvento:
      'https://tenmeetings.com.br/ten-events/#/webinar?evento=ConferenciadeResultados3T22_492',
    linkGravacaoEN: '',
  },
  {
    cliente: 'Armac | DR | 3T22 1/4 | 10/11 10h',
    data: '10/11/2022',
    hora: '10:00',
    proprietario: 'GABI',
    tocarEvento: 'GABI',
    contaZoom: '500',
    gravacaoIngles: 'KENJI',
    linkOficialEvento:
      'https://tenmeetings.com.br/ten-events/#/webinar?evento=ARMAC-3T22_573',
    linkGravacaoEN: '',
  },
  {
    cliente: 'Melnick | DR 3T22 | 11/11 09:30h',
    data: '11/11/2022',
    hora: '09:30',
    proprietario: 'RUSSO',
    tocarEvento: 'RUSSO',
    contaZoom: '500',
    gravacaoIngles: 'RUSSO',
    linkOficialEvento:
      'https://tenmeetings.com.br/ten-events/#/webinar?evento=ConferenciadeResultados3T22-Melnick_615',
    linkGravacaoEN: '',
  },
  {
    cliente: 'Even | DR 3T22 | 11/11 11:45',
    data: '11/11/2022',
    hora: '11:45',
    proprietario: 'RUSSO',
    tocarEvento: 'RUSSO',
    contaZoom: '500',
    gravacaoIngles: 'DANILO',
    linkOficialEvento:
      'https://tenmeetings.com.br/ten-events/#/webinar?evento=ConferenciadeResultados3T22-Even_881',
    linkGravacaoEN: '',
  },
  {
    cliente: 'SANEPAR | DR 3T22 | 07/11 10h',
    data: '07/11/2022',
    hora: '10:00',
    proprietario: 'VENTURA',
    tocarEvento: 'VENTURA',
    contaZoom: '1000',
    gravacaoIngles: 'MICHELLE',
    linkOficialEvento:
      'https://tenmeetings.com.br/ten-events/#/webinar?evento=ConferenciadeResultados3T22_374',
    linkGravacaoEN: '',
  },
  {
    cliente: 'TAESA | DR 3T22 | 10/11 11h',
    data: '10/11/2022',
    hora: '11:00',
    proprietario: 'ALINE',
    tocarEvento: 'ALINE',
    contaZoom: '1000',
    gravacaoIngles: 'FELIPE',
    linkOficialEvento:
      'https://tenmeetings.com.br/ten-events/#/webinar?evento=ConferênciadeResultadosTAESA3T22_492',
    linkGravacaoEN: '',
  },
  {
    cliente: 'CEMIG | DR 3T22 | 16/11 15h',
    data: '16/11/2022',
    hora: '15:00',
    proprietario: 'GABI',
    tocarEvento: 'GABI',
    contaZoom: '500',
    gravacaoIngles: 'VENTURA',
    linkOficialEvento:
      'https://tenmeetings.com.br/ten-events/#/webinar?evento=Cemig-3T22_553',
    linkGravacaoEN: '',
  },
  {
    cliente: 'SLC Agrícola | DR 3T22 | 07/11 10h',
    data: '07/11/2022',
    hora: '10:00',
    proprietario: 'BRENNO',
    tocarEvento: 'ALINE/BRENNO',
    contaZoom: '500',
    gravacaoIngles: 'LUAN',
    linkOficialEvento:
      'https://tenmeetings.com.br/ten-events/#/webinar?evento=ConferênciadeResultados-3T22SLC_957',
    linkGravacaoEN: '',
  },
  {
    cliente: 'Abrapp | AGE | 09/11 10h',
    data: '09/11/2022',
    hora: '10:00',
    proprietario: 'LUIZ',
    tocarEvento: 'LUIZ',
    contaZoom: 'NÃO TEM',
    gravacaoIngles: 'NÃO TEM',
    linkOficialEvento:
      'https://www.tenmeetings.com.br/assembleia/portal/?id=9F617FA09ACB',
    linkGravacaoEN: '',
  },
  {
    cliente: 'RANDON | FR | 01/11 19H',
    data: '01/11/2022',
    hora: '19:00',
    proprietario: 'GABI',
    tocarEvento: 'GUSTAVO E MATHEUS',
    contaZoom: '500',
    gravacaoIngles: 'ALINE VALENTIM',
    linkOficialEvento:
      'https://tenmeetings.com.br/ten-events/#/webinar?evento=Randon-FatoRelevante_525',
    linkGravacaoEN: '',
  },
  {
    cliente: 'Oi | AGE 22 - 18/11* as 11h',
    data: '18/11/2022',
    hora: '11:00',
    proprietario: 'RUSSO',
    tocarEvento: 'RUSSO',
    contaZoom: 'NÃO TEM',
    gravacaoIngles: 'NÃO TEM',
    linkOficialEvento:
      'https://www.tenmeetings.com.br/assembleia/portal/?id=34D5BA00C00B',
    linkGravacaoEN: '',
  },
  {
    cliente: 'RAIZEN | DR 3T22 | 11/11 11h (EN)',
    data: '11/11/2022',
    hora: '11:00',
    proprietario: 'VENTURA',
    tocarEvento: 'GABRIEL+ OTAVIO +',
    contaZoom: '1000',
    gravacaoIngles: 'PEDRO HENRIQUE',
    linkOficialEvento:
      "https://tenmeetings.com.br/ten-events/#/webinar?evento=Raizen-TeleconferenciadeResultados2T22'23_139",
    linkGravacaoEN: '',
  },
  {
    cliente: 'SMARTFIT | DR 3T22 | 10/11 11h',
    data: '10/11/2022',
    hora: '11:00',
    proprietario: 'ALINE',
    tocarEvento: 'GUSTAVO',
    contaZoom: '500',
    gravacaoIngles: 'DAVID',
    linkOficialEvento:
      'https://tenmeetings.com.br/ten-events/#/webinar?evento=ConferenciadeResultados3T22-Smartfit_530',
    linkGravacaoEN: '',
  },
  {
    cliente: 'GRUPO MATHEUS | DR3T22 | 11/11 9h',
    data: '11/11/2022',
    hora: '09:00',
    proprietario: 'RUSSO',
    tocarEvento: 'GUSTAVO E MATHEUS',
    contaZoom: '500',
    gravacaoIngles: 'MARCELO',
    linkOficialEvento:
      'https://tenmeetings.com.br/ten-events/#/webinar?evento=ConferenciadeResultados3T22-GrupoMateus_928',
    linkGravacaoEN: '',
  },
  {
    cliente: 'BR Partners | DR 3T22 | 11/11 às 11:30h',
    data: '11/11/2022',
    hora: '11:30',
    proprietario: 'VENTURA',
    tocarEvento: 'GABI',
    contaZoom: '500',
    gravacaoIngles: 'DAVID',
    linkOficialEvento: '',
    linkGravacaoEN: '',
  },
];
