export const eventosJson = [
  {
    cliente: 'ODONTOPREV | DR 3T22 | 27/10 10h',
    data: '27/10/2022',
    hora: '10:00',
    proprietario: 'ALINE',
    tocarEvento: 'ALINE',
    contaZoom: '500',
    gravacaoIngles: 'MICHELLE',
    linkOficialEvento:
      'https://tenmeetings.com.br/ten-events/#/webinar?evento=VideoconferenciadeResultados3T22-Odontoprev_396',
  },
  {
    cliente: 'Assaí | DR 3T22 | 27/10 11h',
    data: '27/10/2022',
    hora: '11:00',
    proprietario: 'VENTURA',
    tocarEvento: 'VENTURA',
    contaZoom: '1000',
    gravacaoIngles: 'GABI',
    linkOficialEvento:
      'https://tenmeetings.com.br/ten-events/#/webinar?evento=TeleconferenciadeResultados-3T22_812',
  },
  {
    cliente: 'ISA CTEEP | DR 3T22 | 28/10 10h',
    data: '28/10/2022',
    hora: '10:00',
    proprietario: 'RUSSO',
    tocarEvento: 'RUSSO',
    contaZoom: '500',
    gravacaoIngles: 'BRENNO',
    linkOficialEvento:
      'https://tenmeetings.com.br/ten-events/#/webinar?evento=ConferenciadeResultados3T22_651',
  },
  {
    cliente: 'INTELBRAS | DR 3T22 | 01/11 11h',
    data: '01/11/2022',
    hora: '11:00',
    proprietario: 'ALINE',
    tocarEvento: 'ALINE',
    contaZoom: '500',
    gravacaoIngles: 'MICHELLE',
    linkOficialEvento:
      'https://tenmeetings.com.br/ten-events/#/webinar?evento=Intelbras-3T22_500',
  },
  {
    cliente: 'GPA | DR 3T22 | 04/11 10hs',
    data: '04/11/2022',
    hora: '10:00',
    proprietario: 'ALINE',
    tocarEvento: 'ALINE',
    contaZoom: '1000',
    gravacaoIngles: 'GABI',
    linkOficialEvento:
      'https://tenmeetings.com.br/ten-events/#/webinar?evento=ConferênciadeResultados3T22_777',
  },
  {
    cliente: 'Três Tentos Agro | DR 3T22 | 08/11 10h',
    data: '08/11/2022',
    hora: '11:00',
    proprietario: 'BRENNO',
    tocarEvento: 'BRENNO',
    contaZoom: '500',
    gravacaoIngles: 'GABI',
    linkOficialEvento:
      'https://tenmeetings.com.br/ten-events/#/webinar?evento=ConferênciadeResultados-3T22TrêsTentosAgro_924',
  },
  {
    cliente: 'Banco Modal | DR 3T22| 08/11 11h',
    data: '08/11/2022',
    hora: '11:00',
    proprietario: 'RUSSO',
    tocarEvento: 'RUSSO',
    contaZoom: '500',
    gravacaoIngles: 'MICHELLE',
    linkOficialEvento:
      'https://tenmeetings.com.br/ten-events/#/webinar?evento=ConferenciadeResultados3T22-Modal_874',
  },
  {
    cliente: 'ENGIE | DR 3T22 | 09/11 11h',
    data: '09/11/2022',
    hora: '11:00',
    proprietario: 'GABI',
    tocarEvento: 'VENTURA',
    contaZoom: '500',
    gravacaoIngles: 'LUAN EN e BRENNO PT',
    linkOficialEvento:
      'https://tenmeetings.com.br/ten-events/#/webinar?evento=Engie-3T22_915',
  },
  {
    cliente: 'BOA VISTA | DR 3T22 | 10/11 11h',
    data: '10/11/2022',
    hora: '11:00',
    proprietario: 'RUSSO',
    tocarEvento: 'RUSSO',
    contaZoom: '500',
    gravacaoIngles: 'RUSSO',
    linkOficialEvento:
      'https://tenmeetings.com.br/ten-events/#/webinar?evento=BOAS3-ConferenciadeResultados3T22_918',
  },
  {
    cliente: 'Gerdau | DR 3T22 (Imprensa) | 09/11 11h',
    data: '09/11/2022',
    hora: '11:00',
    proprietario: 'ALINE',
    tocarEvento: 'ALINE',
    contaZoom: '500',
    gravacaoIngles: 'MICHELLE',
    linkOficialEvento:
      'https://tenmeetings.com.br/ten-events/#/webinar?evento=VideoconferênciadeResultados3T22-Gerdau(Imprensa)_795',
  },
  {
    cliente: 'Gerdau | DR 3T22 (Analistas/Investidores) | 09/11 14h',
    data: '09/11/2022',
    hora: '14:00',
    proprietario: 'ALINE',
    tocarEvento: 'ALINE',
    contaZoom: '500',
    gravacaoIngles: 'MICHELLE E BRENNO',
    linkOficialEvento:
      'https://tenmeetings.com.br/ten-events/#/webinar?evento=VideoconferênciadeResultados3T22-Gerdau(Analistas/Investidores)_870',
    '': 'https://us06web.zoom.us/w/89487442275?tk=HPTPkicGmWuOijWbpjyeY2r-eyG7XxurBvHX6QvfYM8.DQMAAAAU1d4BYxZHTTRuSmVYMVN5ZXJ1YlY1dmJTU1lBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA',
  },
  {
    cliente: 'ELETROBRAS | DR 3T22 | 10/11 14:30h',
    data: '10/11/2022',
    hora: '14:30',
    proprietario: 'RUSSO',
    tocarEvento: 'RUSSO',
    contaZoom: '500',
    gravacaoIngles: 'RUSSO E MICHELLE',
    linkOficialEvento:
      'https://tenmeetings.com.br/ten-events/#/webinar?evento=ConferenciadeResultados3T22-Eletrobras_220',
  },
  {
    cliente: 'Azul | DR 3T22 | 10/11 12h (EN)',
    data: '10/11/2022',
    hora: '12:00',
    proprietario: 'BRENNO',
    tocarEvento: 'SOUSA E PAULO R.',
    contaZoom: '1000',
    gravacaoIngles: 'NÃO TEM',
    linkOficialEvento:
      'https://tenmeetings.com.br/ten-events/#/webinar?evento=ResultsConferenceAzul3Q22_129',
  },
  {
    cliente: 'Porto Seguro | DR 3T22 | 10/11 11h',
    data: '10/11/2022',
    hora: '11:00',
    proprietario: 'GABI',
    tocarEvento: 'JEAN',
    contaZoom: '500',
    gravacaoIngles: 'VINICIUS',
    linkOficialEvento:
      'https://tenmeetings.com.br/ten-events/#/webinar?evento=Porto-3T22_880',
  },
  {
    cliente: 'HELBOR | DR 3T22 | 10/11 15h',
    data: '10/11/2022',
    hora: '15:00',
    proprietario: 'GABI',
    tocarEvento: 'GABI',
    contaZoom: '500',
    gravacaoIngles: 'KENJI',
    linkOficialEvento:
      'https://tenmeetings.com.br/ten-events/#/webinar?evento=Helbor-3T22_480',
  },
  {
    cliente: 'Grupo Carrefour Brasil | DR 3T22 | 10/11 10h',
    data: '10/11/2022',
    hora: '10:00',
    proprietario: 'RUSSO',
    tocarEvento: 'GABRIEL',
    contaZoom: '1000',
    gravacaoIngles: 'NOME 1',
    linkOficialEvento:
      'https://tenmeetings.com.br/ten-events/#/webinar?evento=ConferenciadeResultados3T22-Carrefour_769',
  },
  {
    cliente: 'Cosan | DR 3T22 | 14/11 14h',
    data: '14/11/2022',
    hora: '14:00',
    proprietario: 'VENTURA',
    tocarEvento: 'VENTURA',
    contaZoom: '1000',
    gravacaoIngles: 'LUAN',
    linkOficialEvento: '',
  },
  {
    cliente: 'Ferbasa | DR 3T22 | 14/11 15h',
    data: '14/11/2022',
    hora: '15:00',
    proprietario: 'GABI',
    tocarEvento: 'GABI',
    contaZoom: '500',
    gravacaoIngles: 'BRENNO',
    linkOficialEvento:
      'https://tenmeetings.com.br/ten-events/#/webinar?evento=Ferbasa-3T22_388',
  },
  {
    cliente: 'FRASLE | DR 3T22 | 10/11 11h',
    data: '10/11/2022',
    hora: '11:00',
    proprietario: 'VENTURA',
    tocarEvento: 'MICHELLE',
    contaZoom: '500',
    gravacaoIngles: 'PEDRO HENRIQUE',
    linkOficialEvento:
      'https://tenmeetings.com.br/ten-events/#/webinar?evento=ConferenciadeResultados3T22_666',
  },
  {
    cliente: 'IOCHPE | DR 3T22 | 10/11 10h',
    data: '10/11/2022',
    hora: '10:00',
    proprietario: 'RUSSO',
    tocarEvento: 'VENTURA',
    contaZoom: '500',
    gravacaoIngles: 'DANI MARKETING',
    linkOficialEvento:
      'https://tenmeetings.com.br/ten-events/#/webinar?evento=ConferenciadeResultados3T22-Iochpe-Maxion_944',
  },
  {
    cliente: 'POSITIVO | DR 3T22 | 10/11 14:30h',
    data: '10/11/2022',
    hora: '14:30',
    proprietario: 'ALINE',
    tocarEvento: 'ALINE',
    contaZoom: '500',
    gravacaoIngles: 'FELIPE',
    linkOficialEvento:
      'https://tenmeetings.com.br/ten-events/#/webinar?evento=Positivo-3T22_327',
  },
  {
    cliente: 'BBM | DR 3T22 | 11/11 10h',
    data: '11/11/2022',
    hora: '10:00',
    proprietario: 'GABI',
    tocarEvento: 'GABRIEL',
    contaZoom: '500',
    gravacaoIngles: 'NÃO TEM',
    linkOficialEvento:
      'https://tenmeetings.com.br/ten-events/#/webinar?evento=BBM-3T22_905',
  },
  {
    cliente: 'VITTIA | DR 3T22 | 11/11 10h',
    data: '11/11/2022',
    hora: '10:00',
    proprietario: 'VENTURA',
    tocarEvento: 'SOUSA',
    contaZoom: '500',
    gravacaoIngles: 'VINICIUS',
    linkOficialEvento:
      'https://tenmeetings.com.br/ten-events/#/webinar?evento=ConferenciadeResultados3T22_269',
  },
  {
    cliente: 'Hapvida | DR 3T22 | 10/11 11h',
    data: '10/11/2022',
    hora: '11:00',
    proprietario: 'ALINE',
    tocarEvento: 'BRENNO',
    contaZoom: '3000',
    gravacaoIngles: 'LUAN',
    linkOficialEvento:
      'https://tenmeetings.com.br/ten-events/#/webinar?evento=Hapvida3T22_869',
  },
  {
    cliente: 'Oi | DR 3T22 | 10/11 11h',
    data: '10/11/2022',
    hora: '11:00',
    proprietario: 'RUSSO',
    tocarEvento: 'A DEFINIR',
    contaZoom: '3000',
    gravacaoIngles: 'NOME 2',
    linkOficialEvento:
      'https://tenmeetings.com.br/ten-events/#/webinar?evento=ResultsConference3Q22_222',
  },
  {
    cliente: 'Priner | DR 3T22 | 11/11 09:30h',
    data: '11/11/2022',
    hora: '09:30',
    proprietario: 'BRENNO',
    tocarEvento: 'VENTURA/JEAN',
    contaZoom: '500',
    gravacaoIngles: 'NÃO TEM',
    linkOficialEvento:
      'https://tenmeetings.com.br/ten-events/#/webinar?evento=ConferênciadeResultados-3T22Priner_125',
  },
  {
    cliente: 'Locaweb | DR 3T22 | 11/11 15h',
    data: '11/11/2022',
    hora: '15:00',
    proprietario: 'RUSSO',
    tocarEvento: 'RUSSO',
    contaZoom: '500',
    gravacaoIngles: 'PEDRO HENRIQUE',
    linkOficialEvento:
      'https://tenmeetings.com.br/ten-events/#/webinar?evento=ConferenciadeResultados3T22-Locaweb_173',
  },
  {
    cliente: 'MILLS | DR 3T22 | 11/11 14h',
    data: '11/11/2022',
    hora: '14:00',
    proprietario: 'RUSSO',
    tocarEvento: 'VENTURA',
    contaZoom: '500',
    gravacaoIngles: 'IAN',
    linkOficialEvento:
      'https://tenmeetings.com.br/ten-events/#/webinar?evento=ConferenciadeResultados3T22-Mills_984',
  },
  {
    cliente: 'Mercantil | DR 3T22 |  11/11 10h',
    data: '11/11/2022',
    hora: '10:00',
    proprietario: 'GABI',
    tocarEvento: 'GABI',
    contaZoom: '500',
    gravacaoIngles: 'KENJI',
    linkOficialEvento:
      'https://tenmeetings.com.br/ten-events/#/webinar?evento=Mercantil-3T22_268',
  },
  {
    cliente: 'Randon | DR 3T22 | 11/11 11h',
    data: '11/11/2022',
    hora: '11:00',
    proprietario: 'GABI',
    tocarEvento: 'MATHEUS',
    contaZoom: '500',
    gravacaoIngles: 'MORENO',
    linkOficialEvento:
      'https://tenmeetings.com.br/ten-events/#/webinar?evento=Randon-3T22_178',
  },
  {
    cliente: 'Multilaser | DR 3T22 | 11/11 09h',
    data: '11/11/2022',
    hora: '09:00',
    proprietario: 'VENTURA',
    tocarEvento: 'MICHELLE',
    contaZoom: '500',
    gravacaoIngles: 'DANI MARKETING',
    linkOficialEvento:
      'https://tenmeetings.com.br/ten-events/#/webinar?evento=ConferenciadeResultados3T22_155',
  },
  {
    cliente: 'Vivara | DR 3T22 | 11/11 11h',
    data: '11/11/2022',
    hora: '11:00',
    proprietario: 'VENTURA',
    tocarEvento: 'VENTURA',
    contaZoom: '500',
    gravacaoIngles: 'IAN',
    linkOficialEvento:
      'https://tenmeetings.com.br/ten-events/#/webinar?evento=vivara3T22_869',
  },
  {
    cliente: 'PETRORECONCAVO | DR 3T22 | 11/11 10h',
    data: '11/11/2022',
    hora: '10:00',
    proprietario: 'VENTURA',
    tocarEvento: 'ALINE',
    contaZoom: '500',
    gravacaoIngles: 'PAULO',
    linkOficialEvento:
      'https://tenmeetings.com.br/ten-events/#/webinar?evento=ConferenciadeResultados3T22_264',
  },
  {
    cliente: 'ENERGISA | DR 3T22 | 11/11 15h',
    data: '11/11/2022',
    hora: '15:00',
    proprietario: 'ALINE',
    tocarEvento: 'ALINE',
    contaZoom: '500',
    gravacaoIngles: 'PAULO',
    linkOficialEvento:
      'https://tenmeetings.com.br/ten-events/#/webinar?evento=ENERGISA3T22_461',
  },
  {
    cliente: 'AGROGALAXY | DR 3T22 | 16/11 11h',
    data: '16/11/2022',
    hora: '11:00',
    proprietario: 'ALINE',
    tocarEvento: 'ALINE',
    contaZoom: '500',
    gravacaoIngles: 'BRENNO',
    linkOficialEvento:
      'https://tenmeetings.com.br/ten-events/#/webinar?evento=Agrogalaxy-3T22_311',
  },
  {
    cliente: 'Eucatex | ID | 11/11 11h',
    data: '11/11/2022',
    hora: '11:00',
    proprietario: 'RUSSO',
    tocarEvento: 'MICHELLE/RAFAEL',
    contaZoom: '500',
    gravacaoIngles: 'NÃO TEM',
    linkOficialEvento: '',
  },
  {
    cliente: 'Zenvia | DR 3T22 | 17/11 12h (EN)',
    data: '17/11/2022',
    hora: '12:00',
    proprietario: 'ALINE',
    tocarEvento: 'GABI',
    contaZoom: '500',
    gravacaoIngles: 'NÃO TEM',
    linkOficialEvento:
      'https://tenmeetings.com.br/ten-events/#/webinar?evento=Zenvia-3Q22_727',
  },
  {
    cliente: 'BRISANET | DR 3T22 | 17/11 13h',
    data: '17/11/2022',
    hora: '13:00',
    proprietario: 'ALINE',
    tocarEvento: 'RUSSO',
    contaZoom: '500',
    gravacaoIngles: 'GABI',
    linkOficialEvento:
      'https://tenmeetings.com.br/ten-events/#/webinar?evento=Brisanet3T22_106',
  },
  {
    cliente: 'Agribrasil | DR 3T22 |  11/11 17:30h',
    data: '11/11/2022',
    hora: '17:30',
    proprietario: 'ALINE',
    tocarEvento: 'ALINE',
    contaZoom: '500',
    gravacaoIngles: 'PAULO',
    linkOficialEvento:
      'https://tenmeetings.com.br/ten-events/#/webinar?evento=Agribrasil3T22_409',
  },
  {
    cliente: 'Banco Inter | DR 3T22 | 09/11 11h (EN)',
    data: '09/11/2022',
    hora: '11:00',
    proprietario: 'GABI',
    tocarEvento: 'GABI',
    contaZoom: '1000',
    gravacaoIngles: 'PEDRO HENRIQUE',
    linkOficialEvento:
      'https://tenmeetings.com.br/ten-events/#/webinar?evento=BancoInter-3T22_405',
  },
  {
    cliente: 'Riachuelo | DR 3T22 | 10/11 13h',
    data: '10/11/2022',
    hora: '13:00',
    proprietario: 'VENTURA',
    tocarEvento: 'VENTURA',
    contaZoom: '500',
    gravacaoIngles: 'DANI MARKETING',
    linkOficialEvento:
      'https://tenmeetings.com.br/ten-events/#/webinar?evento=ConferenciadeResultados3T22_492',
  },
  {
    cliente: 'Armac | DR | 3T22 1/4 | 10/11 11h',
    data: '10/11/2022',
    hora: '11:00',
    proprietario: 'GABI',
    tocarEvento: 'GABI',
    contaZoom: '500',
    gravacaoIngles: 'KENJI',
    linkOficialEvento:
      'https://tenmeetings.com.br/ten-events/#/webinar?evento=ARMAC-3T22_573',
  },
  {
    cliente: 'Melnick | DR 3T22 | 11/11 09:30h',
    data: '11/11/2022',
    hora: '09:30',
    proprietario: 'RUSSO',
    tocarEvento: 'RUSSO',
    contaZoom: '500',
    gravacaoIngles: 'PEDRO HENRIQUE',
    linkOficialEvento:
      'https://tenmeetings.com.br/ten-events/#/webinar?evento=ConferenciadeResultados3T22-Melnick_615',
  },
  {
    cliente: 'Even | DR 3T22 | 11/11 11:45',
    data: '11/11/2022',
    hora: '11:45',
    proprietario: 'RUSSO',
    tocarEvento: 'RUSSO',
    contaZoom: '500',
    gravacaoIngles: 'DANILO',
    linkOficialEvento:
      'https://tenmeetings.com.br/ten-events/#/webinar?evento=ConferenciadeResultados3T22-Even_881',
  },
  {
    cliente: 'SANEPAR | DR 3T22 | 07/11 10h',
    data: '07/11/2022',
    hora: '10:00',
    proprietario: 'VENTURA',
    tocarEvento: 'VENTURA',
    contaZoom: '1000',
    gravacaoIngles: 'MICHELLE',
    linkOficialEvento:
      'https://tenmeetings.com.br/ten-events/#/webinar?evento=ConferenciadeResultados3T22_374',
  },
  {
    cliente: 'TAESA | DR 3T22 | 10/11 11h ',
    data: '10/11/2022',
    hora: '11:00',
    proprietario: 'ALINE',
    tocarEvento: 'ALINE',
    contaZoom: '1000',
    gravacaoIngles: 'FELIPE',
    linkOficialEvento:
      'https://tenmeetings.com.br/ten-events/#/webinar?evento=ConferênciadeResultadosTAESA3T22_492',
  },
  {
    cliente: 'CEMIG | DR 3T22 | 16/11 15h',
    data: '16/11/2022',
    hora: '15:00',
    proprietario: 'GABI',
    tocarEvento: 'GABI',
    contaZoom: '500',
    gravacaoIngles: 'VENTURA',
    linkOficialEvento:
      'https://tenmeetings.com.br/ten-events/#/webinar?evento=Cemig-3T22_553',
  },
  {
    cliente: 'SLC Agrícola | DR 3T22 | 07/11 10h',
    data: '07/11/2022',
    hora: '10:00',
    proprietario: 'ALINE/BRENNO',
    tocarEvento: 'ALINE/BRENNO',
    contaZoom: '500',
    gravacaoIngles: 'LUAN',
    linkOficialEvento:
      'https://tenmeetings.com.br/ten-events/#/webinar?evento=ConferênciadeResultados-3T22SLC_957',
  },
  {
    cliente: 'Abrapp | AGE | 09/11 10h',
    data: '09/11/2022',
    hora: '10:00',
    proprietario: 'LUIZ',
    tocarEvento: 'LUIZ',
    contaZoom: 'NÃO TEM',
    gravacaoIngles: 'NÃO TEM',
    linkOficialEvento:
      'https://www.tenmeetings.com.br/assembleia/portal/?id=9F617FA09ACB',
  },
  {
    cliente: 'RANDON | FR | 01/11 19H',
    data: '01/11/2022',
    hora: '19:00',
    proprietario: 'GABI',
    tocarEvento: 'GABI',
    contaZoom: 'À DEFINIR',
    gravacaoIngles: '',
    linkOficialEvento:
      'https://tenmeetings.com.br/ten-events/#/webinar?evento=Randon-FatoRelevante_525',
  },
  {
    cliente: 'Oi | AGE 22 - 18/11* as 11h',
    data: '18/11/2022',
    hora: '11:00',
    proprietario: 'RUSSO',
    tocarEvento: 'RUSSO',
    contaZoom: 'NÃO TEM',
    gravacaoIngles: '',
    linkOficialEvento: '',
  },
  {
    cliente: 'RAIZEN | DR 3T22 | 11/11 11h',
    data: '11/11/2022',
    hora: '11:00',
    proprietario: 'VENTURA',
    tocarEvento: 'À DEFINIR',
    contaZoom: '1000',
    gravacaoIngles: '',
    linkOficialEvento: '',
  },
  {
    cliente: 'SMARTFIT | DR 3T22 | 10/11 11h (À confirmar)',
    data: '10/11/2022',
    hora: '11:00',
    proprietario: 'À DEFINIR',
    tocarEvento: 'À DEFINIR',
    contaZoom: 'À DEFINIR',
    gravacaoIngles: '',
    linkOficialEvento: '',
  },
  {
    cliente: 'BRF | DR 3T22 |  10/11 (À confirmar)',
    data: '10/11/2022',
    hora: 'À DEFINIR',
    proprietario: 'À DEFINIR',
    tocarEvento: 'À DEFINIR',
    contaZoom: 'À DEFINIR',
    gravacaoIngles: '',
    linkOficialEvento: '',
  },
  {
    cliente: 'Dotz | DR (À confirmar)',
    data: '11/11/2022',
    hora: 'À DEFINIR',
    proprietario: 'BRENNO',
    tocarEvento: 'GABI',
    contaZoom: '1000',
    gravacaoIngles: '',
    linkOficialEvento: '',
  },
];
